### PR TITLE
hal: atmel: added sams70 hal

### PR DESCRIPTION
**Pull request by mcscholtz**
Added the sams70a & sams70b hal downloaded using the atmel start tool

Signed-off-by: Marius Scholtz <mariuss@ricelectronics.com>

### CODE REVIEW

**Comment by mcscholtz** [comment]
@stephanosio This hal library is directly from atmel that is why the licence check is failing? The existing hals for the same70 and samv71 in the repo have the same licence.

**Review by stephanosio — CHANGES_REQUESTED** [review]
Please update the commit message to comply with the [coding guidelines](https://docs.zephyrproject.org/latest/contribute/index.html#identifying-contribution-origin). Also, please specify the DFP version used as well.

You can refer to the following as an example:
https://github.com/zephyrproject-rtos/hal_atmel/commit/3e177f07650959a1292e292b6d40ccf248e45464

**Comment by mcscholtz** [comment]
Thank you for the link to the example commit. 

The PR has been updated it as requested. 
The readme files which were missing were also added, and the cmakefile was changed to add a check for the new soc.

**Review by stephanosio — APPROVED** [review]
This PR, in itself, looks ok -- it just needs a passing Zephyr-side PR before it can be merged.

**Review by nandojve — APPROVED** [review]

**Comment by nandojve** [comment]
Hi @mcscholtz ,

I noted that is missing a `find * type f -print0 | xargs -0 dos2unix -k` in the first commit.

**Comment by nandojve** [comment]
Hi @mcscholtz ,

Please, rebase your code and:

1- check this commit 45cb8f898ffe6ee932fb6d983a113d4e280be40b and make sure you version not suffer same problem
2- I noted that is missing a find * type f -print0 | xargs -0 dos2unix -k in the first commit.

**Comment by mcscholtz** [comment]
@nandojve Thanks. I am a bit bogged down right now and won't get to any of my open tickets for a while. Will circle back to this and other tickets when I get time.

**Pull request closed without merging**
