### PR TITLE
Add missing SUPC SYSC_WPMR register

### PR DESCRIPTION
**Pull request by bjarki-trackunit**
The write protection mode register is placed in the SUPC register address space at offset 0xD4 for the following chips

* SAM4E
* SAM4S
* SAM70
* SAM70B
* SAM71
* SAM71B

This PR adds the register to the `instance/supc.h` files for the aforementioned chips.

Signed-off-by: Bjarki Arge Andreasen <baa@trackunit.com>

### CODE REVIEW

**Comment by nandojve** [comment]
This should follow documentation defined at #31.
These changes should be reflected at component/supc,h to be declared in the instance. This means that registers and macros should be defined if they are missing.

I noted that for SAM3X the WP is defined inside RTC itself. This could be used as a model for others in SUPC.

**Comment by nandojve** [comment]
Hi @bjarki-trackunit ,

Any news?

**Comment by bjarki-trackunit** [comment]
@nandojve Hi, sorry, forgot about this, I am not sure exactly what to do with this weird register... It is placed at an offset relative to SUPC, but it's not part of the SUPC component, so adding it to the instance seems wrong. It seems like the register is only there because Atmel went "where do we place this register for the RTC? wherever there is room I guess" and they put it there.

I can add it to the component just to adhere to the standard, but it will add a bunch of empty space to the SUPC instance since there are 188 bytes from the last register of the SUPC to the SYSC_WPMR register. It will have to look something like

```
typedef struct {
  WoReg SUPC_CR;   /**< \brief (Supc Offset: 0x00) Supply Controller Control Register */
  RwReg SUPC_SMMR; /**< \brief (Supc Offset: 0x04) Supply Controller Supply Monitor Mode Register */
  RwReg SUPC_MR;   /**< \brief (Supc Offset: 0x08) Supply Controller Mode Register */
  RwReg SUPC_WUMR; /**< \brief (Supc Offset: 0x0C) Supply Controller Wake Up Mode Register */
  RwReg SUPC_WUIR; /**< \brief (Supc Offset: 0x10) Supply Controller Wake Up Inputs Register */
  RoReg SUPC_SR;   /**< \brief (Supc Offset: 0x14) Supply Controller Status Register */
  RoReg RESERVED[54];
  RwReg SYSC_WPMR;
} Supc;
```

which will make updating this struct rather slow while debugging, given you have to read all of the reserved registeres.

**Comment by nandojve** [comment]
Let's address this after release.

**Pull request closed without merging**
