### PR TITLE
ext: Import Atmel SAM4L header files from ASF library

### PR DESCRIPTION
**Pull request by nandojve**
Origin: Atmel SAM4L Series Device Support (1.1.61)
License: Apache-2.0
URL: http://packs.download.atmel.com/Atmel.SAM4L_DFP.1.1.61.atpack
Purpose: Introduction of ASF for the SAM4L series.
Maintained-by: External
Signed-off-by: Gerson Fernando Budke nandojve@gmail.com
Zephyr: https://github.com/zephyrproject-rtos/zephyr/pull/26821

### CODE REVIEW

**Comment by nandojve** [comment]
Add 428089c5 to fix BK **error: "_U" redefined**

**Review by ioannisg — APPROVED** [review]

**Comment by ioannisg** [comment]
@nandojve i wonder why the scancode is failing - was it always failing, or the license check started failing now?

**Comment by nandojve** [comment]
Hi @ioannisg, Since I sent this PR license were failing.
The Atmel licenses are MIT compatible and Apache 2.0

**Review by nashif — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Comment by MaureenHelm** [comment]
scancode incorrectly flagged apache-2.0 licensed files as "non-permissive" or "not bsd-x11"

**Pull request merged**
