### PR TITLE
ext: Import Atmel SAM4E header files from ASF library

### PR DESCRIPTION
**Pull request by nandojve**
Origin: Atmel SAM4E Series Device Support (1.1.57)
License: SAM Software Package License
URL: http://packs.download.atmel.com/Atmel.SAM4E_DFP.1.1.57.atpack
Purpose: Introduction of ASF for the SAM4E series.
Maintained-by: External
depends on: https://github.com/zephyrproject-rtos/zephyr/pull/20551

Signed-off-by: Gerson Fernando Budke <nandojve@gmail.com>

### CODE REVIEW

**Comment by galak** [comment]
> Origin: Atmel SAM4E Series Device Support (1.1.57)
> License: Apache-2.0
> URL: http://packs.download.atmel.com/Atmel.SAM4E_DFP.1.1.57.atpack
> Purpose: Introduction of ASF for the SAM4E series.
> Maintained-by: External
> 
> Signed-off-by: Gerson Fernando Budke [nandojve@gmail.com](mailto:nandojve@gmail.com)

Is there a Zephyr PR that utilizes this?

**Comment by nandojve** [comment]
> > Origin: Atmel SAM4E Series Device Support (1.1.57)
> > License: Apache-2.0
> > URL: http://packs.download.atmel.com/Atmel.SAM4E_DFP.1.1.57.atpack
> > Purpose: Introduction of ASF for the SAM4E series.
> > Maintained-by: External
> > Signed-off-by: Gerson Fernando Budke [nandojve@gmail.com](mailto:nandojve@gmail.com)
> 
> Is there a Zephyr PR that utilizes this?

Initial comment was updated with PR number.

**Comment by nandojve** [comment]
Fix correct License name on README

**Comment by nandojve** [comment]
Hi,

**Pull request merged**
